# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            halldorophone
tagline:          'electro acoustic string instrument'
description:      'electro acoustic string instrument'
url:              http://www.halldorophone.info
baseurl:          "/"

author:
  name:
  url:

# Google Analytics / Info hér: https://desiredpersona.com/google-analytics-jekyll/
google_analytics: UA-111864195-1

paginate:         7

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
