# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            halldorophone
tagline:          'electro acoustic string instrument'
description:      'electro acoustic string instrument'
url:              www.halldorophone.info
baseurl:          "/df"

author:
  name:
  url:

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
